import { corsHeaders } from '../_shared/cors.ts';

const apiKey = Deno.env.get('ONSPACE_AI_API_KEY');
const baseUrl = Deno.env.get('ONSPACE_AI_BASE_URL');

// 🧑‍💻 CODING: Claude first (best at code), then DeepSeek (open-source code master)
const CODING_MODELS = [
  'anthropic/claude-opus-4-5',
  'anthropic/claude-sonnet-4-5',
  'deepseek/deepseek-r1',
  'deepseek/deepseek-chat',
  'anthropic/claude-3.5-sonnet',
  'openai/gpt-5-mini',
];

let modelIndex = 0;

const tryAI = async (messages: any[], maxTokens = 3000) => {
  let attempts = 0;
  while (attempts < CODING_MODELS.length) {
    const model = CODING_MODELS[modelIndex];
    try {
      const resp = await fetch(`${baseUrl}/chat/completions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
        body: JSON.stringify({ model, messages, max_tokens: maxTokens }),
      });
      if (!resp.ok) {
        const err = await resp.text();
        if (resp.status === 429 || err.includes('quota') || err.includes('rate limit')) {
          console.log(`[QUOTA] ${model} exhausted, next...`);
          modelIndex = (modelIndex + 1) % CODING_MODELS.length;
          attempts++; continue;
        }
        throw new Error(`API error (${resp.status}): ${err.slice(0, 200)}`);
      }
      const data = await resp.json();
      return { content: data.choices?.[0]?.message?.content ?? '', model };
    } catch (e: any) {
      console.error(`[ERR] ${model}: ${e.message}`);
      modelIndex = (modelIndex + 1) % CODING_MODELS.length;
      attempts++;
    }
  }
  throw new Error('All coding models exhausted.');
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  try {
    const { action, language, challenge, userCode, topic, difficulty } = await req.json();

    if (action === 'generate') {
      // Generate a fresh coding challenge
      const focusTopic = topic ? `focusing on: ${topic}` : 'covering general programming concepts';
      const diffLevel = difficulty || 'easy';
      const prompt = `You are an expert ${language} tutor. Create a Duolingo-style beginner-friendly coding challenge for a student ${focusTopic}.

Difficulty: ${diffLevel} — Keep it simple, clear, and achievable in under 15 minutes.

Return ONLY valid JSON (no markdown fences, no extra text):
{
  "title": "Short catchy name",
  "difficulty": "easy|medium|hard",
  "description": "Clear problem in markdown. Include:\n- What the function should do\n- Input/Output examples in a table or code block\n- Edge cases if any",
  "starterCode": "Clean starter template with type hints/comments, ready to code",
  "testCases": [
    {"input": "example_input", "expectedOutput": "expected_output"}
  ],
  "hints": ["Specific algorithmic hint", "Data structure suggestion"],
  "solution": "Complete, well-commented working solution"
}

Rules:
- Make it appropriate for students (Class 8-12 or college)
- Use real-world relatable scenario (food, games, sports, etc.)
- solution must actually solve the problem correctly`;

      const { content, model } = await tryAI([
        { role: 'system', content: 'You are an expert coding educator. Return ONLY valid JSON.' },
        { role: 'user', content: prompt }
      ]);

      const cleaned = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
      const parsed = JSON.parse(cleaned);
      console.log(`[SUCCESS] Challenge generated by ${model}`);
      return new Response(JSON.stringify({ challenge: parsed, modelUsed: model }), {
        status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    if (action === 'evaluate') {
      // Evaluate user's code
      const sysPrompt = `You are a senior ${language} engineer doing a code review. Be concise, technical, and add ONE funny line.
Evaluate correctness, efficiency, and style. Return ONLY valid JSON.`;

      const prompt = `Challenge: "${challenge?.title}"
Problem: ${challenge?.description}

User's ${language} code:
\`\`\`${language}
${userCode}
\`\`\`

Return ONLY valid JSON:
{
  "passed": true|false,
  "score": 0-100,
  "feedback": "2-3 sentence markdown feedback. Be direct, technical, ONE funny line.",
  "issues": ["Specific bug or issue if any"],
  "timeComplexity": "O(n) etc",
  "improvements": "One-line specific improvement tip"
}`;

      const { content, model } = await tryAI([
        { role: 'system', content: sysPrompt },
        { role: 'user', content: prompt }
      ], 1000);

      const cleaned = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
      const parsed = JSON.parse(cleaned);
      console.log(`[SUCCESS] Code evaluated by ${model}`);
      return new Response(JSON.stringify({ result: parsed, modelUsed: model }), {
        status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    throw new Error('Unknown action');
  } catch (e: any) {
    console.error('[FATAL] solve-coding:', e.message);
    return new Response(JSON.stringify({ error: e.message }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
